# Generated by Django 5.2.7 on 2025-10-24 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_prompt', models.TextField()),
                ('generated_response', models.TextField()),
                ('generated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
