# Generated by Django 5.2.7 on 2025-10-24 04:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='file',
            field=models.FileField(upload_to='contents/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf', 'txt', 'docx', 'md'])]),
        ),
    ]
